service: openup-backend
configValidationMode: error

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-appsync-plugin

custom:
  stage:
    ${opt:stage, self:provider.stage}
  sstApp: 
    ${self:custom.stage}-infrastructure
  appSync:
    ${file(serverless.appsync-api.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  environment:
    tableName: !ImportValue '${self:custom.sstApp}-TableName'
    usersTableName: !ImportValue '${self:custom.sstApp}-usersTableName'
    stage: ${self:custom.stage}

functions:
  insert:
    handler: functions/insert-product.main
    events:
      - http:
          path: products
          method: post
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - !ImportValue '${self:custom.sstApp}-TableArn'

  update:
    handler: functions/update-product.main
    events:
      - http:
          path: products/{id}
          method: put
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
      Resource:
        - !ImportValue '${self:custom.sstApp}-TableArn'

  delete:
    handler: functions/delete-product.main
    events:
      - http:
          path: products/{id}
          method: delete
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
      Resource:
        - !ImportValue '${self:custom.sstApp}-TableArn'

  get:
    handler: functions/get-product.main
    events:
      - http:
          path: products/{id}
          method: get
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - !ImportValue '${self:custom.sstApp}-TableArn'

  list:
    handler: functions/list-all-products.main
    events:
      - http:
          path: products
          method: get
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource:
          - !ImportValue '${self:custom.sstApp}-TableArn'

  syncProductsToAlgolia:
    handler: functions/sync-products-to-algolia.handler
    events:
      - stream:
          type: dynamodb
          arn: !ImportValue '${self:custom.sstApp}-StreamArn'
          batchSize: 100
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - ssm:GetParameters
          - ssm:GetParametersByPath
          - ssm:GetParameter
        Resource:
          - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/foodstock/${self:custom.stage}/algoliaAppID
          - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/foodstock/${self:custom.stage}/algoliaAdminKey

  confirmUserSignup:
    handler: functions/confirm_user_signup.handler
    environment:
        USERS_TABLE: !ImportValue '${self:custom.sstApp}-usersTableName'
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: !ImportValue '${self:custom.sstApp}-usersTableArn'

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireUppercase: false
            RequireSymbols: false
        UsernameAttributes:
          - email
        Schema:
          - AttributeDataType: String
            Name: name
            Required: false
            Mutable: true
        LambdaConfig:
          PostConfirmation: !GetAtt ConfirmUserSignupLambdaFunction.Arn

    UserPoolInvokeConfirmUserSignupLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:invokeFunction
        FunctionName: !Ref ConfirmUserSignupLambdaFunction
        Principal: cognito-idp.amazonaws.com
        SourceArn: !GetAtt CognitoUserPool.Arn

    WebUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref CognitoUserPool
        ClientName: web
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        PreventUserExistenceErrors: ENABLED
  